#parameters:

services:
    cube_common.project_version:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - %kernel.root_dir%
            - %kernel.cache_dir%
    cube_common.user_settings:
        class: CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage
        arguments:
            - "@doctrine"
            - "@security.token_storage"
    cube_common.filtering:
        class: CubeTools\CubeCommonBundle\Filter\FilterService
        arguments:
            - "@request_stack"
        calls:
            - [setPaginator, ['@?knp_paginator']]
