#parameters:

services:
    cube_common.project_version:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - '%kernel.root_dir%'
            - '%kernel.cache_dir%'
    CubeTools\CubeCommonBundle\Project\ProjectVersionGit: '@cube_common.project_version'
    cube_common.user_settings:
        class: CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage
        arguments:
            - "@doctrine"
            - "@security.token_storage"
    CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage: '@cube_common.user_settings'
    cube_common.filtering:
        class: CubeTools\CubeCommonBundle\Filter\FilterService
        arguments:
            - "@request_stack"
        calls:
            - [setPaginator, ['@?knp_paginator']]
    CubeTools\CubeCommonBundle\Filter\FilterService: '@cube_common.filtering'
    cube_common.session_keep_on_success:
        class: CubeTools\CubeCommonBundle\Session\KeepOnSuccessEventListener
        tags:
            - { name: kernel.event_subscriber }
    CubeTools\CubeCommonBundle\Session\KeepOnSuccessEventListener: '@cube_common.session_keep_on_success'
    cube_common.excel.converter:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelConverter
        arguments:
            - "@phpexcel"
    CubeTools\CubeCommonBundle\FileFormat\ExcelConverter: '@cube_common.excel.converter'
    cube_common.excel.reader:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelReader
    CubeTools\CubeCommonBundle\FileFormat\ExcelReader: '@cube_common.excel.reader'
