#parameters:

services:
    cube_common.project_version:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - %kernel.root_dir%
            - %kernel.cache_dir%
