#parameters:

services:
    CubeTools\CubeCommonBundle\Project\ProjectVersionGit:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - '%kernel.root_dir%'
            - '%kernel.cache_dir%'
    cube_common.project_version: '@CubeTools\CubeCommonBundle\Project\ProjectVersionGit'

    CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage:
        class: CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage
        arguments:
            - "@doctrine"
            - "@security.token_storage"
            - "@event_dispatcher"
    cube_common.user_settings: '@CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage'

    CubeTools\CubeCommonBundle\Controller\DevelopmentSupportController:
        class: CubeTools\CubeCommonBundle\Controller\DevelopmentSupportController
        public: true
        arguments:
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            - '@CubeTools\CubeCommonBundle\Project\ProjectVersionGit'
            - '@Symfony\Component\HttpFoundation\RequestStack'

    CubeTools\CubeCommonBundle\Controller\ColumnSelectorController:
        class: CubeTools\CubeCommonBundle\Controller\ColumnSelectorController
        public: true
        calls:
          - [ setUserSettingsStorage, ['@?CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage'] ]

    CubeTools\CubeCommonBundle\Filter\FilterService:
        class: CubeTools\CubeCommonBundle\Filter\FilterService
        arguments:
            - "@request_stack"
        calls:
            - [setPaginator, ['@?knp_paginator']]
    cube_common.filtering: '@CubeTools\CubeCommonBundle\Filter\FilterService'

    CubeTools\CubeCommonBundle\Filter\FilterEntityQueryBuilder:
        class: CubeTools\CubeCommonBundle\Filter\FilterEntityQueryBuilder
    cube_common.session_keep_on_success:
        class: CubeTools\CubeCommonBundle\Session\KeepOnSuccessEventListener
        tags:
            - { name: kernel.event_subscriber }
    CubeTools\CubeCommonBundle\Session\KeepOnSuccessEventListener: '@cube_common.session_keep_on_success'
    cube_common.excel.converter:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelConverter
        arguments:
            - "@phpexcel"
    CubeTools\CubeCommonBundle\FileFormat\ExcelConverter: '@cube_common.excel.converter'
    cube_common.excel.reader:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelReader
    CubeTools\CubeCommonBundle\FileFormat\ExcelReader: '@cube_common.excel.reader'
    CubeTools\CubeCommonBundle\DataHandling\Logs\DataDogAudit:
        class: CubeTools\CubeCommonBundle\DataHandling\Logs\DataDogAudit
        arguments:
            - '@Doctrine\Common\Persistence\ObjectManager'
    CubeTools\CubeCommonBundle\DataHandling\Logs\DataDogAudit\AuditCustomFields:
        class: CubeTools\CubeCommonBundle\DataHandling\Logs\DataDogAudit\AuditCustomFields
        arguments:
            - '@Doctrine\Common\Persistence\ObjectManager'
    CubeTools\CubeCommonBundle\DataHandling\CollectionHandler:
        class: CubeTools\CubeCommonBundle\DataHandling\CollectionHandler
    CubeTools\CubeCommonBundle\Form\ColumnsExtractor:
        class: CubeTools\CubeCommonBundle\Form\ColumnsExtractor
    CubeTools\CubeCommonBundle\Form\EventListener\AnyNoneFilterListener:
        class: CubeTools\CubeCommonBundle\Form\EventListener\AnyNoneFilterListener
        autowire: true
        shared: false
    CubeTools\CubeCommonBundle\Subscriptions\Conditions\Notifications:
        class: CubeTools\CubeCommonBundle\Subscriptions\Conditions\Notifications
        autowire: true
        calls:
            - [setFilterEntityQueryBuilder, ['@CubeTools\CubeCommonBundle\Filter\FilterEntityQueryBuilder']]
    CubeTools\CubeCommonBundle\Subscriptions\Message\ParticipantsGenerator:
        class: CubeTools\CubeCommonBundle\Subscriptions\Message\ParticipantsGenerator
        autowire: true
    CubeTools\CubeCommonBundle\Subscriptions\Message\ContentGenerator:
        class: CubeTools\CubeCommonBundle\Subscriptions\Message\ContentGenerator
        autowire: true
    CubeTools\CubeCommonBundle\Subscriptions\MailSubscription:
        class: CubeTools\CubeCommonBundle\Subscriptions\MailSubscription
        autowire: true
        calls:
            - [setMessageContentGenerator, ['@CubeTools\CubeCommonBundle\Subscriptions\Message\ContentGenerator']]
            - [setMessageParticipantsGenerator, ['@CubeTools\CubeCommonBundle\Subscriptions\Message\ParticipantsGenerator']]
    CubeTools\CubeCommonBundle\Security\VersatileUserProvider:
        class: CubeTools\CubeCommonBundle\Security\VersatileUserProvider
        autowire: true
    CubeTools\CubeCommonBundle\Security\VersatileLdapBindAuthenticationProvider:
        class: CubeTools\CubeCommonBundle\Security\VersatileLdapBindAuthenticationProvider
        abstract: true
        arguments: ['', '', '', '', '', '%security.authentication.hide_user_not_found%']
