#parameters:

services:
    cube_common.project_version:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - %kernel.root_dir%
            - '%kernel.cache_dir%'
    cube_common.user_settings:
        class: CubeTools\CubeCommonBundle\UserSettings\UserSettingsStorage
        arguments:
            - "@doctrine"
            - "@security.token_storage"
    cube_common.filtering:
        class: CubeTools\CubeCommonBundle\Filter\FilterService
        arguments:
            - "@request_stack"
        calls:
            - [setPaginator, ['@?knp_paginator']]
    cube_common.session_keep_on_success:
        class: CubeTools\CubeCommonBundle\Session\KeepOnSuccessEventListener
        tags:
            - { name: kernel.event_subscriber }
    cube_common.excel.converter:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelConverter
        arguments:
            - "@phpexcel"
